//export const dados = 

export const dados109="109|9|QS|Pode ter medo de estranhos"

export const dados149="149|12|QS|É tímido ou nervoso com estranhos "
export const dados150="150|12|QS|Chora quando a mãe ou pai vai embora"
export const dados151="151|12|QS|Possui pessoas e objetos preferidos"
export const dados152="152|12|QS|Demonstra medo em algumas situações"
export const dados153="153|12|QS|Entrega um livro para você quando quer ouvir uma história"
export const dados154="154|12|QS|Repete sons ou reações para conseguir atenção"
export const dados155="155|12|QS|Levanta os braços e as pernas para ajudar na hora de se vestir"
export const dados156="156|12|QS|Brinca de 'esconder e achar o rosto' e 'ciranda'"
export const dados157="157|12|QL|Responde a pedidos simples verbais"
export const dados158="158|12|QL|Usa gestos simples, como balançar a cabeça [simbolizando]  'não' ou acenar 'tchau'"
export const dados159="159|12|QL|Emite sons com alterações no tom (soa mais parecido com  a fala)"
export const dados160="160|12|QL|Diz 'mama' e 'papa' e exclamações como 'uh-oh!'"
export const dados161="161|12|QL|Tenta dizer as palavras que você fala"
export const dados162="162|12|QG|Explora as coisas de formas diferentes, como chacoalhando,  batendo ou arremessando"
export const dados163="163|12|QG|Acha objetos escondidos com facilidade"
export const dados164="164|12|QG|Olha para uma imagem ou objeto certo quando se diz o nome  de tal objeto"
export const dados165="165|12|QG|Imita gestos"
export const dados166="166|12|QG|Começa a usar as coisas corretamente; por exemplo, bebe de  um copo, escova o cabelo"
export const dados167="167|12|QG|Bate dois objetos um contra o outro"
export const dados168="168|12|QG|Coloca os objetos em uma caixa, tira os objetos de uma caixa"
export const dados169="169|12|QG|Solta as coisas sem ajuda"
export const dados170="170|12|QG|Cutuca com o dedo indicador"
export const dados171="171|12|QG|Segue instruções simples como  'pegue o brinquedo'"
export const dados172="172|12|QM|Senta-se sem ajuda"
export const dados173="173|12|QM|Segura para se levantar, caminha segurando nos móveis"
export const dados174="174|12|QM|Pode dar alguns passos sem se apoiar"
export const dados175="175|12|QM|Pode ficar de pé sozinho"
export const dados176="176|12|AJ|Não engatinha"
export const dados177="177|12|AJ|Não consegue ficar de pé com apoio"
export const dados178="178|12|AJ|Não procura objetos que viu você esconder."
export const dados179="179|12|AJ|Não fala palavras simples como 'mama' ou 'papa'"
export const dados180="180|12|AJ|Não aprende gestos como acenar ou balançar a cabeça"
export const dados181="181|12|AJ|Não aponta para objetos"
export const dados182="182|12|AJ|Perde habilidades que já teve"
export const dados183="183|12|OPF|De tempo para ele conhecer e se familiarizar com um novo cuidador. Traga um brinquedo favorito, animal pelúcia ou cobertor para confortar seu filho."
export const dados184="184|12|OPF|Em resposta a comportamentos indesejáveis, diga 'não' com firmeza. Não grite, bata ou dé explicações longas. Uma repreensão de 30 segundos a 1 minuto pode ajudar a redirecionará-lo"
export const dados185="185|12|OPF|Dê a seu filho muitos abraços, beijos e parabenize-o pelo bom comportamento."
export const dados186="186|12|OPF|Passe mais tempo parabenizando um bom comportamento do que punindo um mau comportamento (4 vezes mais encorajamento por bons comportamentos do que redirecionamento por maus comportamentos)."
export const dados187="187|12|OPF|Converse sobre o que você está fazendo. Por exemplo 'mamãe está lavando suas mãos com um a toalha de rosto'."
export const dados188="188|12|OPF|Leia com seu filho diariamente. Faça com que ele vire as páginas. Reveze na descrição das imagens."
export const dados189="189|12|OPF|Fale mais sobre o que ele diz ou tenta dizer, ou para o que aponta. Se apontar para um caminhão e falar 'e' ou 'caminhão', diga, 'sim, é um caminhão azul e grande'"
export const dados190="190|12|OPF|Dê giz de cera e papel, e deixe-o desenhar livremente. Mostre a ele como desenhar linhas para cima e para baixo, e por toda a página. Elogie-o quando tenta copiar as linhas."
export const dados191="191|12|OPF|Brinque com blocos, brinquedos de formas variadas e outros brinquedos que estimulem o uso das mãos"
export const dados192="192|12|OPF|Esconda brinquedos pequenos e outros objetos e faça-o procurá-los."
export const dados193="193|12|OPF|Peça que descreva partes do corpo ou coisas que  vocês veem enquanto andam de carro."
export const dados194="194|12|OPF|Cante canções com ações, como 'A dona aranha' e 'As rodas do ônibus'. Ajude-o seguir as ações com você."
export const dados195="195|12|OPF|Dê potes e panelas ou um instrumento musical como um tambor ou pratos. Incentive-o a fazer barulho."
export const dados196="196|12|OPF|Ofereça muitos lugares seguros para seu filho explorar. (Deixe a casa à prova de bebês. Guarde produtos de limpeza, de lavanderia, de jardinagem e automotivos fora do alcance da criança. Use um portão de segurança e tranque as portas que dão para o exterior."
export const dados197="197|12|OPF|Dê a ele brinquedos de puxar, como caminhões ou um 'carrinho infantil de empurrar'."



